# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

# Command line
# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Command line
# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows

- task: CmdLine@2
  inputs:
    script: 'mkdir d:\a\1\MobEAD' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'drop'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection' # Nome da conexão configurada
    repository: 'jefersong3/unyleya_projeto_cicd_jeferson' # Seu repositório Docker Hub
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
